SELECT count(DISTINCT HEALTHSUPPORTERID)
FROM SUPPORTS
WHERE extract(MONTH FROM DATEOFAUTHORIZATION) = '09' AND extract(YEAR FROM DATEOFAUTHORIZATION) = '2016' AND
      PATIENTID IN (SELECT PATIENTID
                    FROM SICK
                    WHERE DISEASEID = 1);


SELECT count(DISTINCT PATIENTID)
FROM ALERT
WHERE ALERTTYPE = 'low-activity';

SELECT
  FIRSTNAME,
  LASTNAME
FROM PATIENT
WHERE PATIENTID IN (SELECT PATIENTID
                    FROM PATIENT INTERSECT SELECT HEALTHSUPPORTERID
                                           FROM HEALTHSUPPORTER);


SELECT
  FIRSTNAME,
  LASTNAME
FROM PATIENT
WHERE PATIENTID NOT IN (SELECT DISTINCT PATIENTID
                        FROM SICK);

SELECT COUNT(DISTINCT PATIENTID)
FROM OBSERVATION
WHERE OBSERVATIONTIME <> RECORDEDTIME;