DROP SEQUENCE PersonIDSequence;
DROP SEQUENCE ObservationIDSequence;
DROP SEQUENCE RecommendationIDSequence;
DROP SEQUENCE AlertIDSequence;

CREATE SEQUENCE PersonIDSequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ObservationIDSequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RecommendationIDSequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AlertIDSequence
START WITH 1
INCREMENT BY 1;